/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2_banco;

import static java.lang.Character.isDigit;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Dell
 */
public class Interface extends javax.swing.JFrame {
    /**
     * Creates new form Interface
     */
    Cuentas cuentas = new Cuentas();
    public Interface() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cliente_txtidcliente = new javax.swing.JTextField();
        cliente_txtnombre = new javax.swing.JTextField();
        cliente_txtapellidopaterno = new javax.swing.JTextField();
        cliente_txtapellidomaterno = new javax.swing.JTextField();
        cliente_txttelefono = new javax.swing.JTextField();
        cliente_txtemail = new javax.swing.JTextField();
        cliente_txtdireccion = new javax.swing.JTextField();
        cliente_txtbuscar = new javax.swing.JTextField();
        cliente_btneditar = new javax.swing.JLabel();
        cliente_btnguardar = new javax.swing.JLabel();
        cliente_btneliminar = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cliente_btnnuevo = new javax.swing.JLabel();
        cliente_btnbuscar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cuentas_txtclabe = new javax.swing.JTextField();
        cuentas_cbtipocuenta = new javax.swing.JComboBox<String>();
        cuentas_txtidcliente = new javax.swing.JTextField();
        cuentas_txtbuscar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cuentas_btneditar = new javax.swing.JLabel();
        cuentas_btnguardar = new javax.swing.JLabel();
        cuentas_spmonto = new javax.swing.JSpinner();
        cuentas_btneliminar = new javax.swing.JLabel();
        cuentas_btnnuevo = new javax.swing.JLabel();
        cuentas_btnbuscar = new javax.swing.JLabel();
        cuentas_jdcfecha = new com.toedter.calendar.JDateChooser();
        cuentas_lbfecha = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        movimientos_txtidcliente = new javax.swing.JTextField();
        movimientos_cbtipomovimiento = new javax.swing.JComboBox<String>();
        movimientos_txtcuentadestino = new javax.swing.JTextField();
        movimientos_txtbuscar = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        movimientos_spmonto = new javax.swing.JSpinner();
        movimientos_btneditar = new javax.swing.JLabel();
        movimientos_btnguardar = new javax.swing.JLabel();
        movimientos_btneliminar = new javax.swing.JLabel();
        movimientos_btnbuscar = new javax.swing.JLabel();
        movimientos_btnnuevo = new javax.swing.JLabel();
        movimientos_jdcfecha = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        reportes_cbtipocuenta = new javax.swing.JComboBox<String>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        reportes_jdcfechainicio = new com.toedter.calendar.JDateChooser();
        reportes_jdcfechafin = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Cliente:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido Materno:");

        jLabel4.setText("Apellido Paterno:");

        jLabel5.setText("Direccion:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Email:");

        cliente_txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente_txtemailActionPerformed(evt);
            }
        });

        cliente_btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/Editarperron2.0.png"))); // NOI18N
        cliente_btneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliente_btneditarMouseClicked(evt);
            }
        });

        cliente_btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/guardarperron.png"))); // NOI18N
        cliente_btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliente_btnguardarMouseClicked(evt);
            }
        });

        cliente_btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/borrarperron.png"))); // NOI18N
        cliente_btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliente_btneliminarMouseClicked(evt);
            }
        });

        cliente_btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/Nuevoperron.png"))); // NOI18N
        cliente_btnnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliente_btnnuevoMouseClicked(evt);
            }
        });

        cliente_btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/BuscarPerron.png"))); // NOI18N
        cliente_btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cliente_btnbuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cliente_txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(cliente_txtapellidopaterno))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cliente_txtemail, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(cliente_txttelefono)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(49, 49, 49)
                                .addComponent(cliente_txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(cliente_txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cliente_txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cliente_btnbuscar)
                                .addGap(13, 13, 13)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(cliente_txtapellidomaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(cliente_btnnuevo)
                .addGap(18, 18, 18)
                .addComponent(cliente_btneditar)
                .addGap(18, 18, 18)
                .addComponent(cliente_btnguardar)
                .addGap(18, 18, 18)
                .addComponent(cliente_btneliminar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cliente_txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cliente_txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cliente_txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cliente_txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cliente_txtapellidopaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cliente_txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cliente_txtapellidomaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cliente_txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cliente_btnbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cliente_btnnuevo)
                            .addComponent(cliente_btnguardar)
                            .addComponent(cliente_btneliminar))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23))
                    .addComponent(cliente_btneditar))
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Cliente", jPanel1);

        jPanel2.setToolTipText("ll");

        jLabel8.setText("Clave:");

        jLabel9.setText("Fecha:");

        jLabel10.setText("Tipo de Cuenta:");

        jLabel11.setText("Monto:");

        jLabel12.setText("Id Cliente:");

        cuentas_cbtipocuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Deposito", "Ahorro", "Debito" }));

        cuentas_btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/Editarperron2.0.png"))); // NOI18N
        cuentas_btneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentas_btneditarMouseClicked(evt);
            }
        });

        cuentas_btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/guardarperron.png"))); // NOI18N
        cuentas_btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentas_btnguardarMouseClicked(evt);
            }
        });

        cuentas_btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/borrarperron.png"))); // NOI18N
        cuentas_btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentas_btneliminarMouseClicked(evt);
            }
        });

        cuentas_btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/Nuevoperron.png"))); // NOI18N
        cuentas_btnnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentas_btnnuevoMouseClicked(evt);
            }
        });

        cuentas_btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/BuscarPerron.png"))); // NOI18N
        cuentas_btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentas_btnbuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(cuentas_btnnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(cuentas_btneditar)
                        .addGap(18, 18, 18)
                        .addComponent(cuentas_btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cuentas_btneliminar)
                        .addGap(300, 300, 300))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(cuentas_jdcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cuentas_lbfecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cuentas_txtclabe, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cuentas_txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuentas_txtidcliente)
                            .addComponent(cuentas_spmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuentas_cbtipocuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(249, 249, 249)))
                .addComponent(cuentas_btnbuscar)
                .addGap(399, 399, 399))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuentas_btnbuscar)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cuentas_txtclabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuentas_txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(cuentas_jdcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cuentas_lbfecha, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cuentas_cbtipocuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cuentas_spmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cuentas_txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jLabel22)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cuentas_btneditar)
                    .addComponent(cuentas_btnnuevo)
                    .addComponent(cuentas_btnguardar)
                    .addComponent(cuentas_btneliminar))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cuentas", jPanel2);

        jLabel13.setText("Id Cliente:");

        jLabel14.setText("Fecha:");

        jLabel15.setText("Tipo de Movimiento:");

        jLabel16.setText("Monto:");

        jLabel17.setText("Cuenta Destino:");

        movimientos_cbtipomovimiento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Deposito", "Cheque" }));

        movimientos_btneditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/Editarperron2.0.png"))); // NOI18N
        movimientos_btneditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movimientos_btneditarMouseClicked(evt);
            }
        });

        movimientos_btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/guardarperron.png"))); // NOI18N
        movimientos_btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movimientos_btnguardarMouseClicked(evt);
            }
        });

        movimientos_btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/borrarperron.png"))); // NOI18N

        movimientos_btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/BuscarPerron.png"))); // NOI18N
        movimientos_btnbuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movimientos_btnbuscarMouseClicked(evt);
            }
        });

        movimientos_btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/Nuevoperron.png"))); // NOI18N
        movimientos_btnnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movimientos_btnnuevoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel21))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(movimientos_txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(movimientos_jdcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addGap(72, 72, 72)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addGap(28, 28, 28)))
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(movimientos_cbtipomovimiento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(movimientos_txtcuentadestino)
                                            .addComponent(movimientos_spmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(41, 41, 41)
                                .addComponent(movimientos_txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(movimientos_btnbuscar))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(movimientos_btnnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(movimientos_btneditar)
                        .addGap(18, 18, 18)
                        .addComponent(movimientos_btnguardar)
                        .addGap(18, 18, 18)
                        .addComponent(movimientos_btneliminar)))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movimientos_btnbuscar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(movimientos_txtidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movimientos_txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(movimientos_jdcfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(movimientos_cbtipomovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(movimientos_spmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(movimientos_txtcuentadestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(movimientos_btnguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(movimientos_btneditar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(movimientos_btneliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(movimientos_btnnuevo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(93, 93, 93))
        );

        jTabbedPane1.addTab("Movimientos", jPanel3);

        jLabel18.setText("Tipo de Cuenta:");

        jLabel19.setText("Fecha Inicio:");

        jLabel20.setText("Fecha Fin:");

        reportes_cbtipocuenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Deposito", "Ahorro" }));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/DownloadPerron.png"))); // NOI18N

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2_banco/PdfPerron.png"))); // NOI18N

        jButton1.setText("Generar Reporte");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportes_cbtipocuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportes_jdcfechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reportes_jdcfechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(160, 160, 160))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(reportes_cbtipocuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(reportes_jdcfechainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(reportes_jdcfechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jButton1))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reportes", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cliente_txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente_txtemailActionPerformed

    private void cuentas_btneditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentas_btneditarMouseClicked
            
              try{   
                  String Id2=cuentas_txtbuscar.getText();                     
                    if(Id2.equals(""))
                             JOptionPane.showMessageDialog(this, "No ah ingresado la ID");               
                          else{
                             if(!esNumero(Id2))
                                 JOptionPane.showMessageDialog(this, "ID invalida"); 
                             else{
                     String texto=cuentas.Read();
                     String texto2=cuentas.buscar(texto, Id2);
                     if(texto2=="null")
                         JOptionPane.showMessageDialog(this, "No se encontro la id");
                     else
                     {
                                        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
                            String fecha="";
                            String tamclave=cuentas_txtclabe.getText();
                            if(tamclave.length()!=18){
                                JOptionPane.showMessageDialog(null,"CLAVE INVALIDA!!");
                            }else{
                            if(!(cuentas_jdcfecha.getDate()==null)){
                                fecha=dFormat.format(cuentas_jdcfecha.getDate());
                            }
                            
                                     String texto4=cuentas.buscar(texto,cuentas_txtidcliente.getText());
                                     if(texto4.equals("null")){
                                    String cadComp="";
                                    cadComp=cuentas_txtclabe.getText()+"°"
                                    +fecha+"°"
                                    +cuentas_cbtipocuenta.getSelectedItem()+"°"
                                    +cuentas_spmonto.getValue().toString()+"°"
                                    +cuentas_txtidcliente.getText()+"#"+"\n";
                       
                            cuentas.Modificar(texto,Id2,cadComp);
                            JOptionPane.showMessageDialog(null,"SE HA MODIFICADO");
                        }else
                                     {
                                         JOptionPane.showMessageDialog(null,"NUEVO ID INVALIDO");
                                     }
                            }
                     }       
                             }
                         }
                         } catch (Exception ex) {}

    }//GEN-LAST:event_cuentas_btneditarMouseClicked

    private void cuentas_btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentas_btnguardarMouseClicked
        // TODO add your handling code here:
            if( cuentas_txtclabe.getText().length()==18)
            {
                   String cad= cuentas.Read();
                   String comp=cuentas.buscar(cad,cuentas_txtidcliente.getText());
                   if(comp.equals("null"))
                   {
                                        SimpleDateFormat dFormat=new SimpleDateFormat("dd-MM-yyyy");
                            String fecha="";
                            if(!(cuentas_jdcfecha.getDate()==null)){
                                fecha=dFormat.format(cuentas_jdcfecha.getDate());
                            }
                            String cadComp="";
                            cadComp=cuentas_txtclabe.getText()+"°"
                                    +fecha+"°"
                                    +cuentas_cbtipocuenta.getSelectedItem()+"°"
                                    +cuentas_spmonto.getValue().toString()+"°"
                                    +cuentas_txtidcliente.getText()+"#\n";
                                    
                       try {
                           cuentas.Write(cadComp);
                       } catch (Exception ex) {
                       }
                       JOptionPane.showMessageDialog(null,"GUARDADO CORRERCTAMENTE");
                       
                   }else
                   {
                       JOptionPane.showMessageDialog(null,"ID INVALIDO!!");
                   }
            }else
            {
                   JOptionPane.showMessageDialog(null,"CLAVE INVALIDA!!");
            }
             cuentas_txtclabe.setText("");
                        cuentas_lbfecha.setText("");
                        cuentas_cbtipocuenta.setSelectedItem("");
                        cuentas_spmonto.setToolTipText("");
                        cuentas_txtidcliente.setText("");
                        cuentas_jdcfecha.setDate(null);
                        cuentas_spmonto.setValue(0);
                        cuentas_txtbuscar.setText("");
    }//GEN-LAST:event_cuentas_btnguardarMouseClicked

    private void cliente_btneditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente_btneditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente_btneditarMouseClicked

    private void cliente_btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente_btnguardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente_btnguardarMouseClicked

    private void movimientos_btneditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movimientos_btneditarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_movimientos_btneditarMouseClicked

    private void movimientos_btnguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movimientos_btnguardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_movimientos_btnguardarMouseClicked

    private void cliente_btnnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente_btnnuevoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente_btnnuevoMouseClicked

    private void cuentas_btnnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentas_btnnuevoMouseClicked
        // TODO add your handling code here:
        cuentas_txtclabe.setText("");
        cuentas_jdcfecha.setDate(null);
        cuentas_cbtipocuenta.setSelectedIndex(0);
        SpinnerNumberModel nm=new SpinnerNumberModel();
        nm.setMaximum(20000);
        nm.setMinimum(0);
        nm.setStepSize(100);
        cuentas_spmonto.setModel(nm);
        cuentas_txtidcliente.setText("");
        cuentas_lbfecha.setText("");
        
        
        cuentas_txtclabe.setEnabled(true);
        cuentas_jdcfecha.setEnabled(true);
        cuentas_cbtipocuenta.setEnabled(true);
        cuentas_spmonto.setEnabled(true);
        cuentas_txtidcliente.setEnabled(true);
        cuentas_txtbuscar.setEnabled(false);
        cuentas_txtbuscar.setText("");
    }//GEN-LAST:event_cuentas_btnnuevoMouseClicked

    private void cliente_btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente_btnbuscarMouseClicked
                
    }//GEN-LAST:event_cliente_btnbuscarMouseClicked

    private void cuentas_btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentas_btnbuscarMouseClicked
        // TODO add your handling code here
        String Id1=cuentas_txtbuscar.getText();

        if(Id1.equals("")){
            JOptionPane.showMessageDialog(this, "NO INGRESO ID");
             cuentas_txtclabe.setText("");
                        cuentas_lbfecha.setText("");
                        cuentas_cbtipocuenta.setSelectedItem("");
                        cuentas_spmonto.setToolTipText("");
                        cuentas_txtidcliente.setText("");
                        cuentas_jdcfecha.setDate(null);
                        cuentas_spmonto.setValue(0);
                        cuentas_txtbuscar.setText("");
        }else{
            if(!esNumero(Id1))
                JOptionPane.showMessageDialog(this, "ID invalida"); 
            else{
                String texto=cuentas.Read();
                String texto2=cuentas.buscar(texto, Id1);
                if(texto2=="null")
                    JOptionPane.showMessageDialog(this, "No se encontro la id");
                else{
                    String clabe2="";
                    String fecha2="";
                    String tipocuenta2="";
                    String monto2="";
                    String idcliente="";
                    int aux=0;
                    for(int i=0;i<texto2.length();i++){
                        if(texto2.charAt(i)=='°'){
                            aux++;
                        }
                        if(texto2.charAt(i)!='°'){
                            if(aux==0){
                                clabe2+=texto2.charAt(i);
                            }
                            if(aux==1){
                                fecha2+=texto2.charAt(i);
                            }
                            if(aux==2){
                                tipocuenta2+=texto2.charAt(i);
                            }
                            if(aux==3){
                                monto2+=texto2.charAt(i);
                            }
                            if(aux==4){
                                idcliente+=texto2.charAt(i);
                            }
                            
                        }
                    }
                        cuentas_txtclabe.setText(clabe2);
                        cuentas_lbfecha.setText(fecha2);
                        String espa=" ";
                        tipocuenta2=espa+tipocuenta2;
                        cuentas_cbtipocuenta.setSelectedItem(tipocuenta2);
                        String montofn="";
                        for(int p=0;p<monto2.length();p++){
                            if(isDigit(monto2.charAt(p))){
                                montofn+=monto2.charAt(p);
                            }
                            
                        }
                        int a=Integer.parseInt(montofn);
                        cuentas_spmonto.setValue(a);
                        cuentas_txtidcliente.setText(idcliente);
                     
                   // MostrarEnTabla(Id2,Nombre2,Direccion2);
                }
            }
        }
    }//GEN-LAST:event_cuentas_btnbuscarMouseClicked

    private void movimientos_btnbuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movimientos_btnbuscarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_movimientos_btnbuscarMouseClicked

    private void movimientos_btnnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movimientos_btnnuevoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_movimientos_btnnuevoMouseClicked

    private void cliente_btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cliente_btneliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente_btneliminarMouseClicked

    private void cuentas_btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentas_btneliminarMouseClicked
        // TODO add your handling code here:
              
       String Id2=cuentas_txtbuscar.getText();
            if(!esNumero(Id2))
                JOptionPane.showMessageDialog(this, "ID invalida"); 
            else{                        
                String texto=cuentas.Read();
                String texto2=cuentas.buscar(texto, Id2);
                if(texto2=="null")
                    JOptionPane.showMessageDialog(this, "No se encontro la id");
                else{
                    try {                    
                        cuentas.Eliminar(texto, Id2);
                        JOptionPane.showMessageDialog(this,"SE ELIMINO");
                        
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Error");    
                    }                    
                }
            }
         cuentas_txtclabe.setText("");
                        cuentas_lbfecha.setText("");
                        cuentas_cbtipocuenta.setSelectedItem("");
                        cuentas_spmonto.setToolTipText("");
                        cuentas_txtidcliente.setText("");
                        cuentas_jdcfecha.setDate(null);
                        cuentas_spmonto.setValue(0);
                        cuentas_txtbuscar.setText("");
 
    }//GEN-LAST:event_cuentas_btneliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
private Boolean esNumero(String a){
        Boolean x=true;
        for(int i=0;i<a.length();i++){
            if(isDigit(a.charAt(i))){
                x=true;
            }else{
                x=false;
                break;
            }
        }
        return x;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cliente_btnbuscar;
    private javax.swing.JLabel cliente_btneditar;
    private javax.swing.JLabel cliente_btneliminar;
    private javax.swing.JLabel cliente_btnguardar;
    private javax.swing.JLabel cliente_btnnuevo;
    private javax.swing.JTextField cliente_txtapellidomaterno;
    private javax.swing.JTextField cliente_txtapellidopaterno;
    private javax.swing.JTextField cliente_txtbuscar;
    private javax.swing.JTextField cliente_txtdireccion;
    private javax.swing.JTextField cliente_txtemail;
    private javax.swing.JTextField cliente_txtidcliente;
    private javax.swing.JTextField cliente_txtnombre;
    private javax.swing.JTextField cliente_txttelefono;
    private javax.swing.JLabel cuentas_btnbuscar;
    private javax.swing.JLabel cuentas_btneditar;
    private javax.swing.JLabel cuentas_btneliminar;
    private javax.swing.JLabel cuentas_btnguardar;
    private javax.swing.JLabel cuentas_btnnuevo;
    private javax.swing.JComboBox<String> cuentas_cbtipocuenta;
    private com.toedter.calendar.JDateChooser cuentas_jdcfecha;
    private javax.swing.JLabel cuentas_lbfecha;
    private javax.swing.JSpinner cuentas_spmonto;
    private javax.swing.JTextField cuentas_txtbuscar;
    private javax.swing.JTextField cuentas_txtclabe;
    private javax.swing.JTextField cuentas_txtidcliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel movimientos_btnbuscar;
    private javax.swing.JLabel movimientos_btneditar;
    private javax.swing.JLabel movimientos_btneliminar;
    private javax.swing.JLabel movimientos_btnguardar;
    private javax.swing.JLabel movimientos_btnnuevo;
    private javax.swing.JComboBox<String> movimientos_cbtipomovimiento;
    private com.toedter.calendar.JDateChooser movimientos_jdcfecha;
    private javax.swing.JSpinner movimientos_spmonto;
    private javax.swing.JTextField movimientos_txtbuscar;
    private javax.swing.JTextField movimientos_txtcuentadestino;
    private javax.swing.JTextField movimientos_txtidcliente;
    private javax.swing.JComboBox<String> reportes_cbtipocuenta;
    private com.toedter.calendar.JDateChooser reportes_jdcfechafin;
    private com.toedter.calendar.JDateChooser reportes_jdcfechainicio;
    // End of variables declaration//GEN-END:variables
}
